""" Adds a box description to index.css """

ntid = ''


def medium_range(ntid):
    f = open('/srv/http/notes/css/index.css', 'a')
    f.write('/*-------------------------------------------------Styled_Notes ' + str(ntid) + '----------------------*/\n')
    f.write('\n')
    f.write('.box-' + str(ntid) + ' {\n')
    f.write('background-color: transparent;\n')
    f.write('border-radius: 3px;\n')
    f.write('color: #fff;\n')
    f.write('position: absolute;\n')
    f.write('top: 50%;\n')
    f.write('left: 50%;\n')
    f.write('transform: translate(-50%, -50%);\n')
    f.write('width: 500px;\n')
    f.write('height: 700px;\n')
    f.write('transform-style: preserve-3d;\n')
    f.write('perspective: 2000px;\n')
    f.write('transition: .4s;\n')
    f.write('text-align: center; }\n')
    f.write('.box-' + str(ntid) + ':before {\n')
    f.write('content: "";\n')
    f.write('position: absolute;\n')
    f.write('top: 0;\n')
    f.write('left: 0;\n')
    f.write('width: 100%;\n')
    f.write('height: 100%;\n')
    f.write('background: transparent;\n')
    f.write('border-top: 20px solid #fff;\n')
    f.write('border-left: 20px solid #fff;\n')
    f.write('box-sizing: border-box; }\n')
    f.write('.box-' + str(ntid) + ':after {\n')
    f.write('content: "";\n')
    f.write('position: absolute;\n')
    f.write('top: 0;\n')
    f.write('left: 0;\n')
    f.write('width: 100%;\n')
    f.write('height: 100%;\n')
    f.write('border-bottom: 20px solid #fff;\n')
    f.write('border-right: 20px solid #fff;\n')
    f.write('box-sizing: border-box; }\n')
    f.write('.box-' + str(ntid) + ' .fas {\n')
    f.write('font-size: 25px;\n')
    f.write('height: 50px;\n')
    f.write('width: 50px;\n')
    f.write('line-height: 50px !important;\n')
    f.write('background-color: #fff;\n')
    f.write('color: #2C3A47; }\n')
    f.write('.box-' + str(ntid) + ' .fa2 {\n')
    f.write('position: absolute;\n')
    f.write('bottom: 0;\n')
    f.write('right: 0;\n')
    f.write('z-index: 1; }\n')
    f.write('.box-' + str(ntid) + ' .text {\n')
    f.write('position: absolute;\n')
    f.write('top: 30px;\n')
    f.write('left: -30px;\n')
    f.write('width: calc(100% + 60px);\n')
    f.write('height: calc(100% - 60px);\n')
    f.write('background-color: #2C3A47;\n')
    f.write('border-radius: 3px;\n')
    f.write('transition: .4s; }\n')
    f.write('.box-' + str(ntid) + ' .text .fa {\n')
    f.write('position: absolute;\n')
    f.write('top: 0;\n')
    f.write('left: 0; }\n')
    f.write('.box-' + str(ntid) + '.text div {\n')
    f.write('position: absolute;\n')
    f.write('top: 50%;\n')
    f.write('left: 0;\n')
    f.write('transform: translateY(-50%);\n')
    f.write('text-align: center;\n')
    f.write('width: 100%;\n')
    f.write('padding: 30px 60px;\n')
    f.write('line-height: 1.5;\n')
    f.write('box-sizing: border-box; }\n')
    f.write('.box-' + str(ntid) + ' .text div h3 {\n')
    f.write('font-size: 30px;\n')
    f.write('margin-bottom: 5px; }\n')
    f.write('.box-' + str(ntid) + ' .text div p {\n')
    f.write('font-size: 15px; }\n')
    f.write('.box-' + str(ntid) + ':hover {\n')
    f.write('transform: translate(-50%, -50%) rotateY(-20deg) skewY(3deg); }\n')
    f.write('.box-' + str(ntid) + ':hover .text {\n')
    f.write('transform: rotateY(20deg) skewY(-3deg); }\n')
    f.write('\n')
    f.write('\n')
    f.close()


if __name__ == "__main__":
    medium_range(ntid)
